# Generated by Django 3.2.8 on 2022-01-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscraper',
            name='item_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
