# Generated by Django 4.0.1 on 2022-01-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_alter_webscraper_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscraper',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
    ]
