# Generated by Django 4.0.1 on 2022-02-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_alter_webscraper_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscraper',
            name='item_quantity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
